### ISSUE TITLE
Can I input a strange face and output a face of different emotions or poses?

### ISSUE THREAD

**Issue by henryham** [zo7/deconvfaces#10]
Hi~zo7, as I run command 'python3 face.py generate...', I find I can only get the face of what I have trained (Extend Yale face Dataset B).
How can I input a strange face and get the same face of different emotions or poses? :)

**Comment by flynnmd** [comment]
What do you mean by a strange face? You don't input a face to the network, you input the parameters of what you want to draw, i.e. combinations of parameters the network has already seen.

**Comment by henryham** [comment]
Sorry, I haven't expressed clearly.
I have drawn some faces with the params in the single.yaml files. But I can get the faces of different person only by changing the parameter 'id'. So  the number of faces is limited to the number of data I have trained.
I want ask if it is possible to get a 'happy' face from a neutral face not in the training data? like getting a happy face of myself without training all emotions of my face?
Thanks a lot~

**Comment by flynnmd** [comment]
No, this can't do that, it's currently designed to interpolate between known examples, you'd need a different kind of model to do that.
