### ISSUE TITLE
Can you share your dataset?

### ISSUE THREAD

**Issue by DenisSergeevitch** [zo7/deconvfaces#2]
I would like to know, what photos (how many and what resolution of them) are you used to train your own NN, may you share them?

**Comment by DenisSergeevitch** [comment]
Oh, looks like I found it – http://www.socsci.ru.nl:8180/RaFD2/RaFD
Is it correct? 

UPD. Sorry, now I will read blog posts before asking :)

**Comment by flynnmd** [comment]
@DenisSergeevitch Yes, it's also mentioned in the README~

Keep in mind that this is **not** an open dataset, and there are a lot of restrictions on it. One thing that I'm interested in is finding (or making) a more open dataset and adapting this code to it, since there's a lot of potential this could have beyond science.

**Comment by kaihuchen** [comment]
Indeed RaFD only shares their dataset with researchers affiliated with universities, so I  tried but was unable to get it. I also tried to locate the YaleFaces B dataset with no success (all dead links over the internet). 
@zo7 Your experiments look fantastic with great potential in a lot of areas. I got the program installed but unfortunately could not find any dataset to run it with. It would be wonderful if you eventually can find/make any dataset that you can share.

**Comment by morenoh149** [comment]
if one of them is an open dataset I think you can put on github as well and link to it from this project.

**Comment by flynnmd** [comment]
It looks like the Yale Faces B site is down at the moment, it may come back up later. I haven't been able to locate the original data set, but its extension is still around. (Which I used in #3)

I can potentially put the Yale data up here as well, I just need to check that it's ok to redistribute.

**Comment by kaihuchen** [comment]
I managed to find the extended Yale Faces Database B here (among others): http://academictorrents.com/browse.php?search=Yale+Face+Database+B

It does say 'The data format of this database is the same as http://cvc.yale.edu/projects/yalefacesB/yalefacesB.html the Yale Face Database B'

I have no trouble downloading from this site using torrent.
