### ISSUE TITLE
Use a more open dataset

### ISSUE THREAD

**Issue by flynnmd** [zo7/deconvfaces#3]
The RaFD data used for this project is **not** open data, but there is a lot of potential for this to be used in interesting ways outside of academic research.

It would be really great if we could find other data that could be used to generate faces that has a more permissive license. That way non-researchers would be able to tinker around with this, and we would be able to share the weights publicly.

I don't have much time at the moment to do more work for this, but because this project's gotten a lot of interest lately I want to open this as an issue in case anyone's interested in pursuing it.

**Comment by nakosung** [comment]
I have tested against non RaFD data(which is leeched from internet...) and this is the result.
http://imgur.com/gallery/mId5x

**Comment by flynnmd** [comment]
@nakosung that's interesting! How did you source the data / do you have more details about it? It seems to "fade" between examples more than with the RaFD data.

**Comment by nakosung** [comment]
@zo7 Actually the dataset is 1-d(identity only). So we can expect overfitting (much more fade). The data was grabbed from http://www.faceresearch.org/demos/average.

**Comment by flynnmd** [comment]
Ah, there also seems to be much fewer examples as well, which is probably the bigger reason why it overfits.

Perhaps [Extended Yale Face Database B](http://vision.ucsd.edu/~leekc/ExtYaleDatabase/ExtYaleB.html) might be worthwhile to try? (I actually might have a free moment later today / this weekend, so I may try this myself..)

**Comment by flynnmd** [comment]
Just added this, letting it train overnight since my GPU isn't doing anything at the moment. It'll be interesting to see since this data is less consistent than RaFD (background and head position is very inconsistent) but it's 7x the size and varies lighting/pose instead of emotion/orientation.

**Comment by flynnmd** [comment]
Some results [here](http://imgur.com/a/Xm9nv). It can't interpolate identities as well because of the variation (we should expect that) but it does pose and lighting pretty well.

[Video of random generations](https://youtu.be/kNoJLRD8-mY)

**Comment by flynnmd** [comment]
Closing this since the Yale Faces and JAFFE datasets were added and this really needs more refactoring before we can add another
