### ISSUE TITLE
why there is a pooling layer with pool_size=(1,1) before the upsamping layer?

### ISSUE THREAD

**Issue by ssiaw12345** [zo7/deconvfaces#5]
As the title said, there is a pooling layer with pool_size=(1,1) before the upsamping layer which I think don't make sense, such as face.model.build_model line 65

**Comment by flynnmd** [comment]
Hmm I think that when I first implemented it I had it in my head that deconv was basically reverse conv/pooling, which is why that's there. It's mostly harmless, although I wonder if it's unnecessarily eating up GPU memory since it would just make a copy of its input.

**Comment by ssiaw12345** [comment]
Thank you for your prompt reply~

**Comment by flynnmd** [comment]
Yeah thanks for pointing this out ! -- I just removed it and am able to train with larger batch sizes now, so I think it was just eating memory. My bad~
